_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
hotlink: false
origin: 'https://dev-drupal-camp-pune-2023.pantheonsite.io'
origin_dir: sites/default/files
use_imagecache_root: true
verify: false
excluded_extensions: ''
