name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.0'
        check-latest: true

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Global Gulp
      run: npm install -g gulp-cli

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install ddev
      run: ci-scripts/install_ddev.sh

    - name: Install dependencies
      run: ddev composer install

    - name: Debug
      run: ddev blt doctor --no-interaction

    - name: deploy
      run: ddev blt artifact:deploy --no-interaction


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
